### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by xfeep** [kubernetes/kompose#1129]
Commands:

```
$ wget https://raw.githubusercontent.com/gem/oq-engine/master/docker/docker-compose.yml
$ kompose convert -f docker-compose.yml 
```

Errors:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config.parseValidTypesFromSchema(0xc00048b380, 0xc0003c8be0, 0x1e, 0x0, 0xc0003c8be0, 0x1e)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config/schema_helpers.go:82 +0x6db
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config.oneOfMessage(0xc00019f230, 0xc00048b380, 0x1e1d7c0, 0xc00003b000, 0x1e1d240, 0xc00003af80, 0x4f62aa, 0xc0000dc5a8)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config/validation.go:130 +0x505
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config.generateErrorMessages(0xc00019f230, 0xc00048b380, 0xc00047b1c0, 0xc0003f8a10, 0xc00047b1c0)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config/validation.go:218 +0xb24
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config.validateV2(0xc00019ef60, 0x0, 0x0)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config/validation.go:182 +0xe2
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config.MergeServicesV2(0xc0002cc960, 0x1de7180, 0xc0002cc920, 0x1df0320, 0x2f7ef50, 0x7ffc03750769, 0x12, 0xc00019ef60, 0x2f42120, 0xc000515468, ...)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config/merge_v2.go:15 +0x75f
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config.Merge(0xc0002cc960, 0x1de7180, 0xc0002cc920, 0x1df0320, 0x2f7ef50, 0x7ffc03750769, 0x12, 0xc0003eec00, 0x88e, 0xa8e, ...)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/config/merge.go:108 +0x7fb
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/project.(*Project).load(0xc00029a000, 0x7ffc03750769, 0x12, 0xc0003eec00, 0x88e, 0xa8e, 0xc0001e2300, 0xc00019edb0)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/project/project.go:215 +0xc5
github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc00029a000, 0x0, 0x0)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/docker/libcompose/project/project.go:123 +0x168
github.com/kubernetes/kompose/pkg/loader/compose.parseV1V2(0xc0004d9bb0, 0x1, 0x1, 0x1, 0x1, 0x0, 0x7f0f983bf6c0, 0x0)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v1v2.go:67 +0xbf
github.com/kubernetes/kompose/pkg/loader/compose.(*Compose).LoadFile(0x2f7ef50, 0xc0004d9bb0, 0x1, 0x1, 0x0, 0x0, 0x203000, 0x203000, 0x1a)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/compose.go:179 +0x1af
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x1ba2c94, 0x4, 0x0, 0x1bb7130, 0x15, ...)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/pkg/app/app.go:234 +0x112
github.com/kubernetes/kompose/cmd.glob..func3(0x2f4d1e0, 0xc0002cc7a0, 0x0, 0x2)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/cmd/convert.go:95 +0x4d
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x2f4d1e0, 0xc0002cc760, 0x2, 0x2, 0x2f4d1e0, 0xc0002cc760)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:704 +0x2d3
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2f4d620, 0x4, 0x8, 0x0)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:785 +0x2dc
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x2f4d620, 0x4074b0, 0xc00008e058)
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:738 +0x2b
github.com/kubernetes/kompose/cmd.Execute()
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/cmd/root.go:92 +0x2d
main.main()
	/home/wikus/seafile/files/dev/go/src/github.com/kubernetes/kompose/main.go:22 +0x20

```

**Comment by hangyan** [comment]
@xfeep This is an upstream error, we will try to update the vendor to check if they have fix it. The root cause is the `ulimit.nofile`  key, you can delete the ulimit part of service rabbitmq for now. Sorry about the inconvenience

**Comment by xfeep** [comment]
Kompose could report the error position, e.g. `ulimit.nofile` .
