### ISSUE TITLE
Kompose crash

### ISSUE THREAD

**Issue by fx02** [kubernetes/kompose#1494]
DEBU Checking validation of provider: kubernetes
DEBU Checking validation of controller:
DEBU Docker Compose version: 3.5
INFO Network live is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network live is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network live is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network live is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network live is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
INFO Network live is detected at Source, shall be converted to equivalent NetworkPolicy at Destination
panic: Health check must contain a command

goroutine 1 [running]:

goroutine 1 [running]:
github.com/kubernetes/kompose/pkg/transformer/kubernetes.configProbe(0xc000400dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/yayu/go/src/github.com/kubernetes/kompose/pkg/transformer/kubernetes/podspec.go:290 +0x6dd
github.com/kubernetes/kompose/pkg/transformer/kubernetes.(*Kubernetes).UpdateKubernetesObjects.func1(0xc00007e5a8, 0x203000, 0x203000)
        /home/yayu/go/src/github.com/kubernetes/kompose/pkg/transformer/kubernetes/k8sutils.go:539 +0x5c6
github.com/kubernetes/kompose/pkg/transformer/kubernetes.(*Kubernetes).UpdateController(0xc0001b6140, 0x127d328, 0xc00007e480, 0xc0005725a0, 0xc000572590, 0x27, 0xc0004db800)
        /home/yayu/go/src/github.com/kubernetes/kompose/pkg/transformer/kubernetes/kubernetes.go:1520 +0x34b
github.com/kubernetes/kompose/pkg/transformer/kubernetes.(*Kubernetes).UpdateKubernetesObjects(0xc0001b6140, 0xc000036228, 0x6, 0xc0004bb9d0, 0x6, 0xc0004bba10, 0xb, 0xc00035f5f0, 0x27, 0xc0004db800, ...)
        /home/yayu/go/src/github.com/kubernetes/kompose/pkg/transformer/kubernetes/k8sutils.go:633 +0x870
github.com/kubernetes/kompose/pkg/transformer/kubernetes.(*Kubernetes).Transform(0xc0001b6140, 0xc0004a1ec0, 0x10fc433, 0x7, 0xc0004a1b00, 0x100000100, 0x0, 0x0, 0x0, 0x0, ...)
        /home/yayu/go/src/github.com/kubernetes/kompose/pkg/transformer/kubernetes/kubernetes.go:1497 +0x508
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x10fad7d, 0x4, 0x0, 0x0, 0x0, ...)
        /home/yayu/go/src/github.com/kubernetes/kompose/pkg/app/app.go:226 +0x315
github.com/kubernetes/kompose/cmd.glob..func3(0x18b7660, 0xc0004289a0, 0x0, 0x2)
        /home/yayu/go/src/github.com/kubernetes/kompose/cmd/convert.go:123 +0x5d
github.com/spf13/cobra.(*Command).execute(0x18b7660, 0xc000428980, 0x2, 0x2, 0x18b7660, 0xc000428980)
        /home/yayu/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x18b7900, 0xc00004c778, 0xc0003bff78, 0x406365)
        /home/yayu/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/yayu/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kubernetes/kompose/cmd.Execute(...)
        /home/yayu/go/src/github.com/kubernetes/kompose/cmd/root.go:89
main.main()
        /home/yayu/go/src/github.com/kubernetes/kompose/main.go:27 +0x32

**Comment by fx02** [comment]
My bad, had to comment out blank healthcheck:

    healthcheck:
      test: ["NONE"]
