### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by grebois** [kubernetes/kompose#853]
With a ver 2 file works but with the same file in ver 3 I get;

```
$ kompose convert -f docker-compose.am-int.yml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2219a7b]

goroutine 1 [running]:
github.com/kubernetes/kompose/pkg/loader/compose.dockerComposeToKomposeMapping(0xc42016b700, 0x27, 0xc420044220, 0x1, 0x1, 0xc4201b76b0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:321 +0x40b
github.com/kubernetes/kompose/pkg/loader/compose.parseV3(0xc42055d3a0, 0x1, 0x1, 0x1, 0x1, 0x0, 0x30, 0x27dbd20)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:113 +0x22b
github.com/kubernetes/kompose/pkg/loader/compose.(*Compose).LoadFile(0x3700a00, 0xc42055d3a0, 0x1, 0x1, 0xc4201b6f60, 0x0, 0x0, 0x17, 0x15)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/compose.go:165 +0x4d2
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x289b588, 0x4, 0x0, 0x28af58b, 0x15, ...)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/app/app.go:227 +0x145
github.com/kubernetes/kompose/cmd.glob..func3(0x36ce680, 0xc420311c20, 0x0, 0x2)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/cmd/convert.go:95 +0x4d
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x36ce680, 0xc420311be0, 0x2, 0x2, 0x36ce680, 0xc420311be0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:704 +0x2c6
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x36ceb00, 0x36cef80, 0x2493b60, 0x36cec50)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:785 +0x30e
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x36ceb00, 0x0, 0xc42057ff48)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:738 +0x2b
github.com/kubernetes/kompose/cmd.Execute()
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/cmd/root.go:92 +0x31
main.main()
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/main.go:22 +0x20
```

**Comment by surajnarwade** [comment]
@grebois can you paste your `docker-compose` file here ?

**Comment by grebois** [comment]
@surajnarwade can't really, too many secrets, will try to create one to reproduce the error. Just give me 2 days.

**Comment by grebois** [comment]
@surajnarwade here you can reproduce it;

```
version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 443:443
      - 80:80
    environment:
      - USERNAME
      - PASSWORD
```

output:

```
$ sudo kompose convert -f docker-compose.yml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2219a7b]

goroutine 1 [running]:
github.com/kubernetes/kompose/pkg/loader/compose.dockerComposeToKomposeMapping(0xc4203a24c0, 0x1d, 0xc42000ade0, 0x1, 0x1, 0xc4202d8e10)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:321 +0x40b
github.com/kubernetes/kompose/pkg/loader/compose.parseV3(0xc4205472e0, 0x1, 0x1, 0x1, 0x1, 0x0, 0x30, 0x27dbd20)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:113 +0x22b
github.com/kubernetes/kompose/pkg/loader/compose.(*Compose).LoadFile(0x3700a00, 0xc4205472e0, 0x1, 0x1, 0xc4202d8a80, 0x0, 0x0, 0x17, 0x14)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/compose.go:165 +0x4d2
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x289b588, 0x4, 0x0, 0x28af58b, 0x15, ...)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/pkg/app/app.go:227 +0x145
github.com/kubernetes/kompose/cmd.glob..func3(0x36ce680, 0xc4200a2060, 0x0, 0x2)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/cmd/convert.go:95 +0x4d
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x36ce680, 0xc4200a2020, 0x2, 0x2, 0x36ce680, 0xc4200a2020)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:704 +0x2c6
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x36ceb00, 0x36cef80, 0x2493b60, 0x36cec50)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:785 +0x30e
github.com/kubernetes/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x36ceb00, 0x0, 0xc420543f48)
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/vendor/github.com/spf13/cobra/command.go:738 +0x2b
github.com/kubernetes/kompose/cmd.Execute()
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/cmd/root.go:92 +0x31
main.main()
        /home/wikus/dropbox/dev/go/src/github.com/kubernetes/kompose/main.go:22 +0x20

```

**Comment by surajnarwade** [comment]
@grebois , kompose is behaving strict with environment variable, make sure you have already defined environment variables.

I tried following way,

```
export PASSWORD=xyz
```

and it worked,

```
]$ kompose convert -f docker-compose.yml  --stdout 
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --stdout
      kompose.version: 1.3.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: nginx
    name: nginx
  spec:
    ports:
    - name: "443"
      port: 443
      targetPort: 443
    - name: "80"
      port: 80
      targetPort: 80
    selector:
      io.kompose.service: nginx
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml --stdout
      kompose.version: 1.3.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: nginx
    name: nginx
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: nginx
      spec:
        containers:
        - env:
          - name: PASSWORD
            value: xyz
          - name: USERNAME
            value: snarwade
          image: nginx
          name: nginx
          ports:
          - containerPort: 443
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
```

**Comment by grebois** [comment]
But this only happens with version 3, version 2 works fine... try:

```
version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 443:443
      - 80:80
    environment:
      - USERNAME
      - PASSWORD
```

**Comment by cdrage** [comment]
@grebois Thanks for the bug report. Yup. Version 3 *should* automatically pick up the environment variables. Looks to be an issue upstream. We'll investigate it and push out a fix!

**Comment by grebois** [comment]
@cdrage thanks!

**Comment by yogi-emorphis** [comment]
Hello,
I am using Window 7 (64 Bit). When I am trying for configure rinkeby using "geth --rinkeby" command I am getting following error : 
Panic: runtime error: invalid memory address or nil pointer dereference  [signal 0xc0000005 code=0x0 addr=0x0 pc=0xb88a07] 
Please details find below : 
C:\Users\yogendra>geth --rinkeby
WARN [12-14|19:10:09] No etherbase set and no accounts found as default
INFO [12-14|19:10:09] Starting peer-to-peer node               instance=Geth/v1.
7.3-stable-4bb3c89d/windows-amd64/go1.9
INFO [12-14|19:10:09] Allocated cache and file handles         database=C:\\User
s\\yogendra\\AppData\\Roaming\\Ethereum\\rinkeby\\geth\\chaindata cache=128 hand
les=1024
INFO [12-14|19:10:09] Initialised chain configuration          config="{ChainID:
 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzant
ium: 1035301 Engine: clique}"
INFO [12-14|19:10:09] Initialising Ethereum protocol           versions="[63 62]
" network=4
INFO [12-14|19:10:09] Loaded most recent local header          number=0 hash=634
1fd…67e177 td=1
INFO [12-14|19:10:09] Loaded most recent local full block      number=0 hash=634
1fd…67e177 td=1
INFO [12-14|19:10:09] Loaded most recent local fast block      number=0 hash=634
1fd…67e177 td=1
INFO [12-14|19:10:09] Loaded local transaction journal         transactions=0 dr
opped=0
INFO [12-14|19:10:09] Regenerated local transaction journal    transactions=0 ac
counts=0
INFO [12-14|19:10:09] Starting P2P networking
INFO [12-14|19:10:11] UDP listener up                          self=enode://c719
de22207c8c2a0ce540017eae6a43d8c2b8d37dd1caaa2d0350d55ed9657d25e263ae94be7528466c
e029521eab8706bbac9571b8d98082b109601852ea01@0.0.0.0:30303
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb88a07]

goroutine 85 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc042e5c04
0)
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.
go:417 +0x337
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
        C:/gopath/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.
go:112 +0x10b

>> Please guide me, how can I resolve this issue. your answer would be appreciated.

**Comment by cdrage** [comment]
@yogi-emorphis can you please post your docker-compose.yaml file?

**Comment by yogi-emorphis** [comment]
@cdrage  Thanks for reply. I am not using docker, any other way for resolving ?

**Comment by surajnarwade** [comment]
@yogi-emorphis is this kompose related issue ?

**Comment by yogi-emorphis** [comment]
No , I am just trying to configure rinkeby.

**Comment by surajnarwade** [comment]
Probably this is wrong place to ask question regarding rinkeby.

**Comment by yogi-emorphis** [comment]
@surajnarwade May be you are right but I am facing same error. May be I will get any idea why are occurring this error.

**Comment by cdrage** [comment]
@yogi-emorphis rinkeby uses go-etherium, I'd suggest opening up an issue with your error here: https://github.com/ethereum/go-ethereum

**Comment by hangyan** [comment]
close by #926
